### ISSUE TITLE
doesn't replace anything

### ISSUE THREAD

**Issue by noaccessl** [Be1zebub/Small-GLua-Things#3]
[`shit_characters.lua`](https://github.com/Be1zebub/Small-GLua-Things/blob/master/shit_characters.lua)
It returns the same string
```lua
print( ("Hêllõ wõrld"):gsub("[%z\x01-\x7F\xC2-\xF4][\x80-\xBF]*", shit_characters) )
```
![image](https://user-images.githubusercontent.com/54954576/226354813-8f96b366-54df-46c2-a52c-d823478f12b2.png)

Here's how `string.gsub` works 
![image](https://user-images.githubusercontent.com/54954576/226355324-4fc210fd-eba8-4cd9-b54b-da3681e1be81.png)
So the table should be like this:
```lua
{ ["character"] = "replacement" }
```
And here's the proper code:
```lua
for char, shit in pairs({
	a = {"à","â","ã","å"},
	e = {"è","é","ê","ê","ë"},
	i = {"ì", "í", "î", "ï"},
	o = {"ó","ò","ô","õ"},
	u = {"ù", "ú", "û", "ü"},
	c = {"ç"},
	n = {"ñ"}
}) do
	for _, v in ipairs(shit) do
		shit_characters[v] = char
	end
end
```

**Comment by Be1zebub** [comment]
woops..
solved: https://github.com/Be1zebub/Small-GLua-Things/commit/335849ac4b32f70b959dae0988c1d83e2c09e715
next time, feel free todo pr, instead of creating an issue
